4244 - Add more mixins
infor-design/design-system pull request #453
Opened 2020-09-10 20:17 UTC by jmacaluso711

**Explain the _details_ for making this change. What existing problem does the pull request solve?**
Adding some position mixins

**Related github/jira issue (required)**:
related to #4244

**Steps necessary to review your pull request (required)**:
- pull branch
- `npm run build:mixins`
- check the dist folder and make sure the mixins build properly

2020-09-10 21:24 UTC, EdwardCoyle approved these changes
:banana: Great additions, just found one thing below

2020-09-10 21:24 UTC, EdwardCoyle commented on scripts/node/build-mixins.js
> +  rigth: 'right',
```suggestion
  right: 'right',
```

2020-09-14 13:30 UTC, tmcconechy requested changes
@jmacaluso711 which mixins does this add? I think that the idea is that the spacing setting should add these properties.

Was trying to keep the ui.config.js file compatible with tailwind in case someone wanted it.  And some of the random keys are just added https://github.com/infor-design/design-system/blob/3.0.x/scripts/node/build-mixins.js#L201 https://github.com/tailwindlabs/tailwindcss/blob/master/stubs/defaultConfig.stub.js

Can you list the mixins desired/added and we can work though the best way to add them?

2020-09-14 14:04 UTC, tmcconechy commented
Ok cool. Yeah i think that would be nice. Not sure this makes it incompatible those probably would be ignored.

- for position: add the rules in directly here https://github.com/infor-design/design-system/blob/3.0.x/scripts/node/build-mixins.js#L201
- for left, right, bottom, top? maybe this is fine what i had done is making the spacing generate the margins ect... https://github.com/infor-design/design-system/blob/3.0.x/scripts/node/build-mixins.js#L133 but looking again this is more convoluted that the config.

So maybe this is ok for now

2020-09-14 20:50 UTC, jmacaluso711 commented
@tmcconechy Does anything need to change in this PR?

2020-09-15 13:45 UTC, tmcconechy commented
Lets just go with this for now.

2020-09-15 13:45 UTC, tmcconechy approved these changes

2020-09-15 13:45 UTC, merged